import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import TableQrCode from '@/components/TableQrCode'
import Description from '@/components/Description'
import KitchenTable from '@/components/KitchenTable'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Kitchen Sync Demo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.sectionOneContainer}>
          <TableQrCode qrUrl="https://firebasestorage.googleapis.com/v0/b/kitchensync-fd489.appspot.com/o/tableOneQr.png?alt=media&token=8692d98f-2aea-4ae5-b1db-f21f818c6763"  style={styles.qrImageContainer1} tableNumber={1}/>
          <Description/>
          <TableQrCode qrUrl="https://firebasestorage.googleapis.com/v0/b/kitchensync-fd489.appspot.com/o/tableTwoQr.png?alt=media&token=2949f0a0-ab72-4dd8-b056-4096704f8542"  style={styles.qrImageContainer2} tableNumber={2}/>
        </div>
        <KitchenTable />
        
      </main>
    </>
  )
}
